//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaborateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collaborateur()
        {
            this.IsEligible = true;
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Cin { get; set; }
        public string Cnss { get; set; }
        public string Poste { get; set; }
        public Nullable<System.DateTime> DateDebutTravail { get; set; }
        public string Banque { get; set; }
        public bool IsEligible { get; set; }
        public string Adresse { get; set; }
    
        public virtual Civilite Civilite { get; set; }
    }
}
