//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande
    {
        public int Id { get; set; }
        public System.DateTime DateCreation { get; set; }
        public Nullable<System.DateTime> DateDebutTraitement { get; set; }
        public Nullable<System.DateTime> DateFinTraitement { get; set; }
    
        public virtual TypeAttestation TypeAttestation { get; set; }
        public virtual Collaborateur Collaborateur { get; set; }
        public virtual Statut Statut { get; set; }
        public virtual Collaborateur Assistante { get; set; }
    }
}
